# Generated by Django 5.2.1 on 2025-11-25 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PENDING', 'En attente de revue'), ('REVIEW', 'En cours de revue'), ('INTERVIEW', 'Convoqué(e) en entretien'), ('ACCEPTED', 'Accepté(e)'), ('REJECTED', 'Refusé(e)'), ('CANCELED', 'Annulé(e)')], max_length=10, verbose_name='Ancien Statut')),
                ('new_status', models.CharField(choices=[('PENDING', 'En attente de revue'), ('REVIEW', 'En cours de revue'), ('INTERVIEW', 'Convoqué(e) en entretien'), ('ACCEPTED', 'Accepté(e)'), ('REJECTED', 'Refusé(e)'), ('CANCELED', 'Annulé(e)')], max_length=10, verbose_name='Nouveau Statut')),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historiquement de Candidature',
                'verbose_name_plural': 'Historiques de Candidatures',
                'ordering': ['-date_changement'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='lettre_motivation/', verbose_name='Lettre de Motivation')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente de revue'), ('REVIEW', 'En cours de revue'), ('INTERVIEW', 'Convoqué(e) en entretien'), ('ACCEPTED', 'Accepté(e)'), ('REJECTED', 'Refusé(e)'), ('CANCELED', 'Annulé(e)')], default='PENDING', max_length=10, verbose_name='Statut Actuel')),
                ('commentaires', models.TextField(blank=True, verbose_name="Notes de l'Entreprise")),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(limit_choices_to={'user_type': 'CANDIDAT'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
