# Generated by Django 5.2.1 on 2025-11-25 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='offers.joboffer', verbose_name="Offre d'Emploi/Stage"),
        ),
        migrations.AddField(
            model_name='applicationhistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.application', verbose_name='Candidature'),
        ),
        migrations.AddField(
            model_name='applicationhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidat', 'offer')},
        ),
    ]
