# Generated by Django 5.2.1 on 2025-11-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_expediteur', models.CharField(max_length=50)),
                ('email_expediteur', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=150)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
    ]
