# Generated by Django 5.2.1 on 2025-11-25 11:38

import datetime
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name="Type d'Offre")),
            ],
            options={
                'verbose_name': "Type d'Offre",
                'verbose_name_plural': "Types d'Offres",
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('exigences', models.TextField(verbose_name='Exigences/ Qualifications')),
                ('contract_type', models.CharField(choices=[('CDI', 'contract à Durée Indéterminée'), ('CDD', 'Contract à Durée Déterminée'), ('INTERIM', 'Intérim'), ('STAGE', 'Stage'), ('FREELANCE', 'Freelance/ Consultant')], default='STAGE', max_length=15, verbose_name='Type de contract')),
                ('remuneration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rémunération')),
                ('localisation', models.CharField(max_length=100, verbose_name='Ville/ Région')),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField(default=datetime.date(2025, 12, 25), verbose_name='Date Limite de Candidature')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_offers', to='accounts.companyprofile', verbose_name='Entreprise')),
                ('required_skills', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Compétences Requises')),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'ordering': ['-date_publication'],
            },
        ),
    ]
